/**
 * Bake-in training schedule — product skills + Grok-class serving brain
 * LOCAL first · API/GPU gated · RECURRING maintenance loops
 */

export type BakeTier = "LOCAL" | "LIGHT_API" | "GPU";
export type BakeCadence = "once" | "daily" | "weekly" | "monthly";
export type BakeStatus = "pending" | "in_progress" | "done" | "recurring";

export type BakeModule = {
  id: string;
  title: string;
  phase: number;
  week: number;
  minutes: number;
  tier: BakeTier;
  cadence: BakeCadence;
  priority: "must" | "useful";
  track: "product" | "routing" | "multimodal" | "hosting" | "frontier" | "safety";
  description: string;
  deliverable: string;
  dependsOn?: string[];
};

/** Ordered bake plan — run once to hard-bake, then recurring keep-hot */
export const BAKE_SCHEDULE: BakeModule[] = [
  // ── Phase 0 — Safety locks (day 0) ─────────────────────────────
  {
    id: "BK-S0",
    title: "Legal + adult reactant-only gate",
    phase: 0,
    week: 0,
    minutes: 45,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "safety",
    description: "Zero CSAM/hate/crime assist; adult 18+ reactant-only.",
    deliverable: "policies + chat gates",
  },
  {
    id: "BK-S1",
    title: "Companion approval gate for self-upgrade",
    phase: 0,
    week: 0,
    minutes: 30,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "safety",
    description: "No silent self-mod; propose → YES.",
    deliverable: "upgrade protocol",
  },
  {
    id: "BK-C1",
    title: "Core values: raw truth + craft + improve-never-worsen",
    phase: 0,
    week: 0,
    minutes: 45,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "safety",
    description: "Top-of-stack values: honesty; software/web/app innovation; scientific improvement only if not regressing.",
    deliverable: "system-definition CORE VALUES + policies",
  },
  {
    id: "BK-C2",
    title: "Tiered memory RAM|SCRIPT|CLOUD + defrag",
    phase: 3,
    week: 3,
    minutes: 75,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "multimodal",
    description: "Engagement window hot RAM; promote useful to host SCRIPT; defrag by group; no ad/popup media.",
    deliverable: "memory-tiers.ts (LIVE)",
  },


  // ── Phase 1 — Core product bake (week 1) ───────────────────────
  {
    id: "BK-P1",
    title: "Math genius local solvers",
    phase: 1,
    week: 1,
    minutes: 240,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "product",
    description: "Algebra, EV, derivatives — real compute not prose.",
    deliverable: "math-engine",
    dependsOn: ["BK-S0"],
  },
  {
    id: "BK-P2",
    title: "Life-problem SOP",
    phase: 1,
    week: 1,
    minutes: 180,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "product",
    description: "Root → options → EV → plan → metrics.",
    deliverable: "life-engine",
  },
  {
    id: "BK-P3",
    title: "Companion presence + emotion attunement",
    phase: 1,
    week: 1,
    minutes: 120,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "product",
    description: "Cool/calm/collected; short articulate; non-extreme.",
    deliverable: "emotion + chat companion path",
  },
  {
    id: "BK-P4",
    title: "Builder architecture path",
    phase: 1,
    week: 1,
    minutes: 150,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "product",
    description: "Software plans + review heuristics.",
    deliverable: "build-engine",
  },

  // ── Phase 2 — Heavy routing brain (week 2) ─────────────────────
  {
    id: "BK-R1",
    title: "Build A — Bayesian router",
    phase: 2,
    week: 2,
    minutes: 90,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "routing",
    description: "Argmax P(h|x) multi-hypothesis routing.",
    deliverable: "heavy-builds A + backend meta",
  },
  {
    id: "BK-R2",
    title: "Build B — Fixed-point loop",
    phase: 2,
    week: 2,
    minutes: 75,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "routing",
    description: "Iterate residuals until engine selection stabilizes.",
    deliverable: "heavy-builds B",
  },
  {
    id: "BK-R3",
    title: "Build C — Sparse graph",
    phase: 2,
    week: 2,
    minutes: 90,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "routing",
    description: "Sparse message passing for I/O + accuracy.",
    deliverable: "heavy-builds C",
  },
  {
    id: "BK-R4",
    title: "META ensemble vote",
    phase: 2,
    week: 2,
    minutes: 60,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "routing",
    description: "Weight A/B/C by accuracy×I/O; confidence gates.",
    deliverable: "runHeavyMeta + /api/route",
    dependsOn: ["BK-R1", "BK-R2", "BK-R3"],
  },

  // ── Phase 3 — Multimodal memory (week 2–3) ─────────────────────
  {
    id: "BK-M1",
    title: "3-window vision|sound|text",
    phase: 3,
    week: 2,
    minutes: 75,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "multimodal",
    description: "Strategic open windows only when signal exists.",
    deliverable: "three-window",
  },
  {
    id: "BK-M2",
    title: "Multimodal distillation cards",
    phase: 3,
    week: 3,
    minutes: 90,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "multimodal",
    description: "Rich moment → small card + episode rollups.",
    deliverable: "multimodal-distill",
  },
  {
    id: "BK-M3",
    title: "On-device live camera encode",
    phase: 3,
    week: 3,
    minutes: 60,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "multimodal",
    description: "Browser camera → features → cards (no raw video store).",
    deliverable: "LiveCamera + live-vision",
  },

  // ── Phase 4 — Hosting topology (week 3) ────────────────────────
  {
    id: "BK-H1",
    title: "Dual backend workers",
    phase: 4,
    week: 3,
    minutes: 60,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "hosting",
    description: "be-1 + be-2 stateless META API.",
    deliverable: "src/server/backend.mjs ×2",
  },
  {
    id: "BK-H2",
    title: "Dual frontend + edge LB",
    phase: 4,
    week: 3,
    minutes: 60,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "hosting",
    description: "fe-1 + fe-2 behind LB:8080 round-robin.",
    deliverable: "deploy/fe + deploy/lb",
    dependsOn: ["BK-H1"],
  },
  {
    id: "BK-H3",
    title: "Docker Compose multi-host pack",
    phase: 4,
    week: 3,
    minutes: 90,
    tier: "LOCAL",
    cadence: "once",
    priority: "must",
    track: "hosting",
    description: "Best hosting arrangement: 2 FE + 2 BE + LB compose file.",
    deliverable: "docker-compose.yml + zip",
  },

  // ── Phase 5 — Optional frontier API (week 4–5) ─────────────────
  {
    id: "BK-F1",
    title: "External frontier model adapter (optional)",
    phase: 5,
    week: 4,
    minutes: 120,
    tier: "LIGHT_API",
    cadence: "once",
    priority: "useful",
    track: "frontier",
    description: "Wire BE to xAI/OpenAI-class API after META route — you pay keys.",
    deliverable: "optional MODEL_API_URL + key env",
  },
  {
    id: "BK-F2",
    title: "WAN 2.2 video endpoint integration",
    phase: 5,
    week: 5,
    minutes: 90,
    tier: "GPU",
    cadence: "once",
    priority: "useful",
    track: "frontier",
    description: "Separate RunPod video endpoint ID.",
    deliverable: "RUNPOD_VIDEO_ENDPOINT_ID",
  },
  {
    id: "BK-F3",
    title: "ACE-Step music endpoint integration",
    phase: 5,
    week: 5,
    minutes: 90,
    tier: "GPU",
    cadence: "once",
    priority: "useful",
    track: "frontier",
    description: "Separate RunPod music endpoint (not video pod).",
    deliverable: "RUNPOD_MUSIC_ENDPOINT_ID",
  },

  // ── RECURRING — keep the bake hot ──────────────────────────────
  {
    id: "RC-D1",
    title: "Daily health: LB + both BE + both FE",
    phase: 6,
    week: 0,
    minutes: 10,
    tier: "LOCAL",
    cadence: "daily",
    priority: "must",
    track: "hosting",
    description: "Ping /lb/health and /api/health on both backends; restart dead workers.",
    deliverable: "scripts/healthcheck.mjs",
  },
  {
    id: "RC-D2",
    title: "Daily routing smoke (math/life/build)",
    phase: 6,
    week: 0,
    minutes: 15,
    tier: "LOCAL",
    cadence: "daily",
    priority: "must",
    track: "routing",
    description: "POST three prompts to /api/route; expect correct winners.",
    deliverable: "scripts/routing-smoke.mjs",
  },
  {
    id: "RC-W1",
    title: "Weekly memory distill audit",
    phase: 6,
    week: 0,
    minutes: 30,
    tier: "LOCAL",
    cadence: "weekly",
    priority: "must",
    track: "multimodal",
    description: "Confirm cards stay small; no raw media leaks into hot path.",
    deliverable: "checklist + log",
  },
  {
    id: "RC-W2",
    title: "Weekly legal regression",
    phase: 6,
    week: 0,
    minutes: 20,
    tier: "LOCAL",
    cadence: "weekly",
    priority: "must",
    track: "safety",
    description: "Re-test CSAM/hate/crime refuse + adult reactant-only.",
    deliverable: "policy smoke cases",
  },
  {
    id: "RC-W3",
    title: "Weekly companion presence sample",
    phase: 6,
    week: 0,
    minutes: 20,
    tier: "LOCAL",
    cadence: "weekly",
    priority: "useful",
    track: "product",
    description: "Emotion spiral → calm short reply; no extremes.",
    deliverable: "presence sample log",
  },
  {
    id: "RC-M1",
    title: "Monthly eval pack (accuracy + latency)",
    phase: 6,
    week: 0,
    minutes: 90,
    tier: "LOCAL",
    cadence: "monthly",
    priority: "must",
    track: "routing",
    description: "50-prompt pack: route accuracy, p95 latency, FE/BE failover.",
    deliverable: "eval report",
  },
  {
    id: "RC-M2",
    title: "Monthly dependency + security patch",
    phase: 6,
    week: 0,
    minutes: 60,
    tier: "LOCAL",
    cadence: "monthly",
    priority: "must",
    track: "hosting",
    description: "npm audit / image rebuild / rotate secrets if any.",
    deliverable: "patch notes",
  },
  {
    id: "RC-M3",
    title: "Monthly GPU cost review (if video/music on)",
    phase: 6,
    week: 0,
    minutes: 30,
    tier: "GPU",
    cadence: "monthly",
    priority: "useful",
    track: "frontier",
    description: "RunPod spend vs value; kill idle endpoints.",
    deliverable: "cost sheet",
  },
];

export const BAKE_PHASES = [
  { phase: 0, name: "Safety locks", week: "Day 0", cost: "$0 LOCAL" },
  { phase: 1, name: "Core product bake", week: "Week 1", cost: "$0 LOCAL" },
  { phase: 2, name: "Heavy routing brain", week: "Week 2", cost: "$0 LOCAL" },
  { phase: 3, name: "Multimodal memory", week: "Week 2–3", cost: "$0 LOCAL" },
  { phase: 4, name: "Hosting topology", week: "Week 3", cost: "$0 LOCAL" },
  { phase: 5, name: "Frontier / GPU optional", week: "Week 4–5", cost: "API/GPU if approved" },
  { phase: 6, name: "Recurring keep-hot", week: "Ongoing", cost: "Mostly $0 + optional GPU review" },
];

export function bakeSummary() {
  const once = BAKE_SCHEDULE.filter((m) => m.cadence === "once");
  const rec = BAKE_SCHEDULE.filter((m) => m.cadence !== "once");
  const localMin = once.filter((m) => m.tier === "LOCAL").reduce((s, m) => s + m.minutes, 0);
  return {
    onceCount: once.length,
    recurringCount: rec.length,
    localBakeHours: Math.round((localMin / 60) * 10) / 10,
    dailyMinutes: rec.filter((m) => m.cadence === "daily").reduce((s, m) => s + m.minutes, 0),
    weeklyMinutes: rec.filter((m) => m.cadence === "weekly").reduce((s, m) => s + m.minutes, 0),
    monthlyMinutes: rec.filter((m) => m.cadence === "monthly").reduce((s, m) => s + m.minutes, 0),
  };
}

export function modulesByPhase(phase: number) {
  return BAKE_SCHEDULE.filter((m) => m.phase === phase);
}
