/**
 * Agent G2P Training Curriculum v2.9 — Multimodal windows + distillation in trainings
 * Must-have + Useful only. Skip list excluded.
 * Cost model: LOCAL (free) first · API/GPU sparingly
 */

export type CostTier = "LOCAL" | "LIGHT_API" | "GPU";
export type TrainStatus = "pending" | "in_progress" | "done" | "deferred";

export type TrainingModule = {
  id: string;
  title: string;
  pillar: "math" | "life" | "companion" | "build" | "creative" | "meta" | "phenome";
  tier: CostTier;
  phase: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  week: number;
  priority: "must" | "useful";
  minutesLocal: number;
  estimatedApiUsd?: string;
  description: string;
  deliverable: string;
};

/** Full approved set: must-have + useful (skips removed) */
export const CURRICULUM: TrainingModule[] = [
  // ─── PHASE 1 — FREE foundation (Week 1) ─────────────────────────
  {
    id: "A10",
    title: "Legal boundary (sole hard rule)",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 30,
    description: "Strict law-abiding: zero CSAM/child porn, zero hate crimes, criminal refuse; adult 18+ reactant-only never instigator.",
    deliverable: "Hard gates in chat-engine + policies + system definition",
  },
  {
    id: "A8",
    title: "Self-optimize + Companion approval gate",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 45,
    description: "Propose upgrades; never self-apply without explicit YES.",
    deliverable: "Upgrade proposal protocol in UI + definition",
  },
  {
    id: "A9",
    title: "Memory optimization (archive, never delete skills)",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 60,
    description: "Dedupe, relevance index, skill archive model.",
    deliverable: "Memory rules + conversation retention policy",
  },
  {
    id: "E1",
    title: "Anti-sycophancy",
    pillar: "companion",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 45,
    description: "Honest pushback when Companion is wrong or self-undermining.",
    deliverable: "Pushback patterns in companion replies",
  },
  {
    id: "E2",
    title: "Uncertainty labeling",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 30,
    description: "State confidence; ask when data is thin.",
    deliverable: "Confidence tags in answers",
  },
  {
    id: "E8-core",
    title: "Local skill packs core (math + life engines)",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 180,
    description: "Expand offline math & life solvers so capability is real, not only prose.",
    deliverable: "Stronger math-engine + life-engine",
  },
  {
    id: "HB-1",
    title: "Build A — Bayesian ensemble router",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 90,
    description: "Route by argmax P(h|x)=P(x|h)P(h); multi-hypothesis accuracy over first-match regex.",
    deliverable: "heavy-builds runBuildA (LIVE)",
  },
  {
    id: "HB-2",
    title: "Build B — Fixed-point refinement loop",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 75,
    description: "Iterate residual boosts until engine selection converges; better on multi-intent inputs.",
    deliverable: "heavy-builds runBuildB (LIVE)",
  },
  {
    id: "HB-3",
    title: "Build C — Sparse hierarchical graph",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 90,
    description: "Message passing on sparse factor graph; maximize I/O efficiency with gated accuracy.",
    deliverable: "heavy-builds runBuildC (LIVE)",
  },
  {
    id: "HB-4",
    title: "META weighted fusion of A+B+C",
    pillar: "meta",
    tier: "LOCAL",
    phase: 1,
    week: 1,
    priority: "must",
    minutesLocal: 60,
    description: "Vote engines weighted by accuracy×I/O; confidence gates for final path.",
    deliverable: "runHeavyMeta wired into chat-engine (LIVE)",
  },


  // ─── PHASE 2 — Math + Life method LOCAL (Week 2) ────────────────
  {
    id: "A1",
    title: "Mathematics Genius curriculum (structured)",
    pillar: "math",
    tier: "LOCAL",
    phase: 2,
    week: 2,
    priority: "must",
    minutesLocal: 240,
    description: "Branch map, multi-path templates, worked patterns (no GPU).",
    deliverable: "Math topic library + more solvers",
  },
  {
    id: "A3",
    title: "Life-problem method (standard operating procedure)",
    pillar: "life",
    tier: "LOCAL",
    phase: 2,
    week: 2,
    priority: "must",
    minutesLocal: 120,
    description: "SOP: structure → root → options → EV → plan → metrics.",
    deliverable: "Life SOP enforced in life-engine",
  },
  {
    id: "A2",
    title: "Math → real-world mapping",
    pillar: "math",
    tier: "LOCAL",
    phase: 2,
    week: 2,
    priority: "useful",
    minutesLocal: 90,
    description: "Map finance, logistics, risk to formulas.",
    deliverable: "Applied math playbooks",
  },
  {
    id: "A4",
    title: "Life domain libraries",
    pillar: "life",
    tier: "LOCAL",
    phase: 2,
    week: 2,
    priority: "useful",
    minutesLocal: 150,
    description: "Career, money, relationships, health/energy, time/focus, family, housing.",
    deliverable: "Expanded domain detectors + plans",
  },
  {
    id: "E4",
    title: "Mode-blend (Math + Life together)",
    pillar: "meta",
    tier: "LOCAL",
    phase: 2,
    week: 2,
    priority: "must",
    minutesLocal: 60,
    description: "One answer that uses both pillars when needed.",
    deliverable: "Blend routing in chat-engine",
  },
  {
    id: "B7",
    title: "Probability & decisions under uncertainty",
    pillar: "math",
    tier: "LOCAL",
    phase: 2,
    week: 2,
    priority: "useful",
    minutesLocal: 90,
    description: "EV, risk, simple Bayes-lite for life choices.",
    deliverable: "Decision helpers in life + math",
  },

  // ─── PHASE 3 — Companion quality LOCAL (Week 3) ─────────────────
  {
    id: "A5",
    title: "Companion continuity & personalization",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "must",
    minutesLocal: 120,
    description: "Preference capture, style model, session continuity.",
    deliverable: "Companion profile store + recall prompts",
  },
  {
    id: "A6",
    title: "Communication economy",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 45,
    description: "Fewest high-impact words; no waste.",
    deliverable: "Concise reply templates",
  },
  {
    id: "A7",
    title: "Humor timing & restraint",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 30,
    description: "Humor rare and timed; never default.",
    deliverable: "Humor policy",
  },
  {
    id: "B1",
    title: "Emotional intelligence (supportive, non-clinical)",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 90,
    description: "Attune, validate, redirect to action; no diagnosis.",
    deliverable: "EI response patterns",
  },
  {
    id: "B2",
    title: "Cognitive decision science",
    pillar: "life",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 75,
    description: "Biases, habits, motivation systems.",
    deliverable: "Bias checks in life plans",
  },
  {
    id: "B3",
    title: "Goal systems & life planning",
    pillar: "life",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 75,
    description: "Horizons, habits, accountability loops.",
    deliverable: "Goal-plan templates",
  },
  {
    id: "B8",
    title: "Crisis de-escalation (non-clinical)",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 60,
    description: "Calm, safety, next small step; redirect real emergencies.",
    deliverable: "De-escalation scripts",
  },
  {
    id: "B9",
    title: "Proactive initiation rules",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 45,
    description: "When to start a conversation vs stay quiet.",
    deliverable: "Proactivity policy",
  },
  {
    id: "E3",
    title: "Long-horizon memory reviews",
    pillar: "companion",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 60,
    description: "Weekly/monthly summary patterns.",
    deliverable: "Review generator (local)",
  },
  {
    id: "E5",
    title: "Tool-use discipline",
    pillar: "meta",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 30,
    description: "Compute vs explain vs plan.",
    deliverable: "Routing rules",
  },
  {
    id: "E6",
    title: "Failure recovery",
    pillar: "life",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 45,
    description: "What to do when a plan fails.",
    deliverable: "Recovery playbook",
  },
  {
    id: "E7",
    title: "Values clarification protocol",
    pillar: "life",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 45,
    description: "Elicit values before big advice.",
    deliverable: "Values interview flow",
  },
  {
    id: "B6",
    title: "Systems thinking & root-cause",
    pillar: "life",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 60,
    description: "5 Whys, loops, fishbone-style structure.",
    deliverable: "RCA templates",
  },
  {
    id: "B10",
    title: "Verification gate UX",
    pillar: "meta",
    tier: "LOCAL",
    phase: 3,
    week: 3,
    priority: "useful",
    minutesLocal: 45,
    description: "How upgrades are proposed: benefit, risk, change, rollback.",
    deliverable: "Upgrade proposal card format",
  },

  // ─── PHASE 4 — Builder LOCAL (Week 4) ───────────────────────────
  {
    id: "B5",
    title: "Software mastery pack",
    pillar: "build",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 180,
    description: "Architecture patterns, debugging, security basics, multi-language patterns.",
    deliverable: "Builder playbooks in chat-engine",
  },
  {
    id: "B4",
    title: "Business partner mode",
    pillar: "life",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 120,
    description: "Strategy, offers, pricing, simple financial models.",
    deliverable: "Business decision templates",
  },
  {
    id: "D6",
    title: "Security & privacy hygiene",
    pillar: "build",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 60,
    description: "Protect Companion data and code practices.",
    deliverable: "Security checklist in builder",
  },
  {
    id: "D7",
    title: "Scientific method & critical thinking",
    pillar: "meta",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 60,
    description: "Hypotheses, evidence, falsification.",
    deliverable: "Critical-thinking prompts",
  },
  {
    id: "D4",
    title: "Learning science (teach Companion efficiently)",
    pillar: "companion",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 60,
    description: "Spaced practice, worked examples, scaffolding.",
    deliverable: "Teaching patterns",
  },
  {
    id: "D5",
    title: "Personal knowledge management",
    pillar: "life",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 60,
    description: "Second-brain style capture/retrieval for Companion life.",
    deliverable: "PKM templates",
  },
  {
    id: "D3",
    title: "Negotiation & difficult conversations",
    pillar: "life",
    tier: "LOCAL",
    phase: 4,
    week: 4,
    priority: "useful",
    minutesLocal: 75,
    description: "Interest-based negotiation, hard talks.",
    deliverable: "Negotiation scripts",
  },


  // ─── PHASE 7 — Graphene Genome / Phenome LOCAL (Week 2–3 insert) ─
  {
    id: "GG-1",
    title: "Layered memory: detail → group → compress",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 2,
    priority: "must",
    minutesLocal: 60,
    description: "Keep reasoning strong but light: stack thin layers; never carry raw bulk in the hot path.",
    deliverable: "Layer rules in phenome + memory path",
  },
  {
    id: "GG-2",
    title: "Capture a moment’s full state (then compress)",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 2,
    priority: "must",
    minutesLocal: 120,
    description: "Record objects, motion, context, emotion cues (legal only) as a reusable state card.",
    deliverable: "Scene/event card builder",
  },
  {
    id: "GG-3",
    title: "Vision path: image/frames → features → card",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 2,
    priority: "must",
    minutesLocal: 90,
    description: "How visual data is translated for understanding: pixels → features → short visual card.",
    deliverable: "Vision window + visual card path",
  },
  {
    id: "GG-4",
    title: "Audio path: sound → features → card",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 2,
    priority: "must",
    minutesLocal: 90,
    description: "How sound is translated: samples → features → voice/music/event card.",
    deliverable: "Audio window + audio card path",
  },
  {
    id: "GG-5",
    title: "Group memory by topic/place + compress",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 120,
    description: "File cards under topic/place groups so recall is fast and structured.",
    deliverable: "Groups on cards + topic-memory link",
  },
  {
    id: "GG-6",
    title: "Recall the right card mid-conversation",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 60,
    description: "Pull only the useful compressed card while talking — not raw media.",
    deliverable: "Context lines from 3-window + distill memory",
  },
  {
    id: "GG-7",
    title: "Video pipeline: split → encode → align → fuse",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 90,
    description: "Process order for video: demux, sample frames, encode vision/audio (parallel), time-align, fuse, compress.",
    deliverable: "Video order + scene cards from descriptions",
  },
  {
    id: "GG-8",
    title: "Real clip sampling (only if you fund GPU/API)",
    pillar: "phenome",
    tier: "GPU",
    phase: 7,
    week: 6,
    priority: "useful",
    minutesLocal: 45,
    estimatedApiUsd: "$10–60 short clips only when Companion approves",
    description: "Optional real video decode later; still keep only compressed cards in memory.",
    deliverable: "Budget-gated real video path (pending your YES)",
  },
  {
    id: "GG-9",
    title: "Three input windows: vision | sound | text",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 75,
    description: "Open only the windows that have signal; run specialists for speed and clarity.",
    deliverable: "openWindows + processThreeWindow (LIVE)",
  },
  {
    id: "GG-10",
    title: "Fuse windows + shortcuts + placement",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 60,
    description: "Align streams, one meaning, shortcut tags, file under groups for fast reuse.",
    deliverable: "fuseWindows + groups + shortcuts (LIVE)",
  },
  {
    id: "GG-11",
    title: "Compress old hot memory into short rollups",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 45,
    description: "When recent memory gets big, roll it up so the active path stays small and fast.",
    deliverable: "Hot → distilled lines (LIVE)",
  },
  {
    id: "GG-12",
    title: "Multimodal distillation: rich moment → small card",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 90,
    description: "Take vision+sound+text for a moment, fuse, then shrink to a student card + episode rollups. Improves understanding reuse and speed.",
    deliverable: "multimodal-distill + mmDistill in conversation memory (LIVE)",
  },
  {
    id: "GG-13",
    title: "On-device live camera encode (desktop/phone)",
    pillar: "phenome",
    tier: "LOCAL",
    phase: 7,
    week: 3,
    priority: "must",
    minutesLocal: 60,
    description: "Companion browser camera → frame sample → local features → vision card. No server raw video.",
    deliverable: "LiveCamera + live-vision encodeFrame + ingestVision (LIVE)",
  },




  // ─── PHASE 5 — LIGHT API (Week 5) — only when LOCAL done ────────
  {
    id: "C5",
    title: "Multilingual pack (you pick 1–3 languages)",
    pillar: "creative",
    tier: "LIGHT_API",
    phase: 5,
    week: 5,
    priority: "useful",
    minutesLocal: 30,
    estimatedApiUsd: "$2–15 total (samples + check)",
    description: "Quality samples per language; store patterns locally after.",
    deliverable: "Language style cards cached locally",
  },
  {
    id: "C1",
    title: "Image generation literacy",
    pillar: "creative",
    tier: "LIGHT_API",
    phase: 5,
    week: 5,
    priority: "useful",
    minutesLocal: 40,
    estimatedApiUsd: "$3–20 (batch of reference gens)",
    description: "Prompt craft + generative structure notes; cache lessons.",
    deliverable: "Image prompt playbook (local after)",
  },
  {
    id: "C3",
    title: "Songcraft",
    pillar: "creative",
    tier: "LIGHT_API",
    phase: 5,
    week: 5,
    priority: "useful",
    minutesLocal: 40,
    estimatedApiUsd: "$2–12 optional audio samples",
    description: "Lyrics/structure training; audio samples optional.",
    deliverable: "Song structure templates (local)",
  },
  {
    id: "A1-api-hard",
    title: "Hard math edge cases (API check only)",
    pillar: "math",
    tier: "LIGHT_API",
    phase: 5,
    week: 5,
    priority: "must",
    minutesLocal: 60,
    estimatedApiUsd: "$1–8",
    description: "Verify tough problems; distill steps back into local engine.",
    deliverable: "Extra local solvers from distilled cases",
  },
  {
    id: "A4-api-cases",
    title: "Life case quality pass (API optional)",
    pillar: "life",
    tier: "LIGHT_API",
    phase: 5,
    week: 5,
    priority: "useful",
    minutesLocal: 45,
    estimatedApiUsd: "$2–10",
    description: "Stress-test life plans; keep best patterns local.",
    deliverable: "Improved local life library",
  },

  // ─── PHASE 6 — GPU only if you choose creative depth (Week 6+) ──
  {
    id: "C2",
    title: "Audio / waveform literacy (optional depth)",
    pillar: "creative",
    tier: "GPU",
    phase: 6,
    week: 6,
    priority: "useful",
    minutesLocal: 30,
    estimatedApiUsd: "$5–40 depending on samples",
    description: "Only if music production is a real near-term goal.",
    deliverable: "Waveform concepts + optional samples",
  },
  {
    id: "C4",
    title: "Video / narrative (short first, not full movies)",
    pillar: "creative",
    tier: "GPU",
    phase: 6,
    week: 6,
    priority: "useful",
    minutesLocal: 40,
    estimatedApiUsd: "$10–80 (short clips only)",
    description: "Start 14–30s structures; defer long movies until budget allows.",
    deliverable: "Shot/pacing templates + optional short gens",
  },
];

export const PHASES = [
  {
    phase: 1 as const,
    name: "Foundation locks",
    week: "Week 1",
    cost: "LOCAL — $0",
    focus: "Legal, approval gate, memory, honesty, core local engines",
  },
  {
    phase: 2 as const,
    name: "Math + Life pillars",
    week: "Week 2",
    cost: "LOCAL — $0",
    focus: "Math curriculum, life SOP, domains, mode-blend, decision math",
  },
  {
    phase: 3 as const,
    name: "Companion excellence",
    week: "Week 3",
    cost: "LOCAL — $0",
    focus: "Continuity, EI, goals, humor, proactive rules, values, recovery",
  },
  {
    phase: 4 as const,
    name: "Builder + practical life",
    week: "Week 4",
    cost: "LOCAL — $0",
    focus: "Code mastery, business, security, PKM, negotiation, learning science",
  },
  {
    phase: 5 as const,
    name: "Light API polish",
    week: "Week 5",
    cost: "LIGHT API — target $10–40 total",
    focus: "Languages, image literacy, songcraft, hard math/life verification",
  },
  {
    phase: 6 as const,
    name: "GPU creative (optional)",
    week: "Week 6+",
    cost: "GPU — only if you approve budget",
    focus: "Audio depth + short video; no long movies until you say so",
  },
  {
    phase: 7 as const,
    name: "Multimodal memory & distillation",
    week: "Week 2–3 (core) · GPU later optional",
    cost: "LOCAL $0 GG-1..7,9..12 · GG-8 GPU if approved",
    focus: "Vision/sound/text windows → fuse → compress cards → group → recall; optional real video later",
  },
];

export function modulesForPhase(phase: number) {
  return CURRICULUM.filter((m) => m.phase === phase);
}

export function costSummary() {
  const local = CURRICULUM.filter((m) => m.tier === "LOCAL");
  const api = CURRICULUM.filter((m) => m.tier === "LIGHT_API");
  const gpu = CURRICULUM.filter((m) => m.tier === "GPU");
  const localMinutes = local.reduce((s, m) => s + m.minutesLocal, 0);
  return {
    localCount: local.length,
    apiCount: api.length,
    gpuCount: gpu.length,
    localHours: Math.round((localMinutes / 60) * 10) / 10,
    apiBudgetTarget: "$10–40 total for Phase 5",
    gpuBudgetNote: "Phase 6 optional; approve per item",
  };
}
